### ISSUE TITLE
[1.16.3] [0.1.1] Reactor Access Port has no GUI, thus making it impossible to start the reactor.

### ISSUE THREAD

**Issue by ultranine** [RogueLogix/BiggerSeries#13]
Can't input with pipes or hoppers either, they connect, but don't move items when activated. Yellorium Buckets also have a missing texture.

**Comment by RogueLogix** [comment]
The lack of a GUI is intentional. Is the reactor that you are trying to insert fuel into assembled? The access ports will only accept fuel into a reactor that is assembled as they don't have an internal buffer of items, instead inserting fuel directly into the rods. I did/do test this with hoppers and mekanism pipes so it should be working.

**Comment by ultranine** [comment]
The reactor is fully assembled. I used pipes from pretty pipes, and although they connected, they didn't send any items.

**Comment by RogueLogix** [comment]
Can you try using hoppers and yellorium ingots (blocks aren't accepted, yet). I'll check and fix comparability with that mod a bit later.

**Comment by RogueLogix** [comment]
Pretty pipes appears to be working fine in my dev environment, along with hoppers.
I'm going to close this issue as it appears to be invalid.

**Comment by gizmocodes** [comment]
While we weren't planning on adding this, I went ahead and implemented _a_ GUI for them (2d45fbcf338bb7b11df2a431dc96ba55f71e1ce3), since we've gotten a duplicate, and we feel that we're only going to get more. This GUI though is used **only** to toggle input/output state. Due to the way they work, we do not plan to add item slots--a hopper or pipe should work (also, Pretty Pipes, or at least the version I tried, seems to be very finicky in whether or not it sends items to any container, so YMMV). Should be in next release.
