### ISSUE TITLE
Suggestion: change the licence to (A)GPL

### ISSUE THREAD

**Issue by M-i-k-o-t-o** [RogueLogix/BiggerSeries#29]
Considering the dishonest behaviour displayed by the creator of Extreme Reactors 2 where he previously stole and closed the source of Big Reactors I believe that it is extremely likely that he is going to do the same with the source of this mod. Changing the licence into a copyleft one would be the easiest way to prevent him and other hostile actors from acting on it.

**Comment by RogueLogix** [comment]
I have reason to believe that he specifically wont, but you do bring up a good point about other hostile actors. As weird as it sounds though, I do actually want people to be able to take the code closed source. Not the mod as a whole though, but I want people to be able to take a large chunk of it, use it in their project, and if they want that project to be closed source, so be it. So, I'm not sure how i want to proceed with the license, or what I really want it to be. It is hard if not impossible to find a license that does that correctly.

As it stands right now, I cant change everything from MIT, as i have copied code from BR, as MIT requires MIT code to stay under MIT (ps: that does mean that good sections of ZeroCore and ExtremeReactors are required to be under MIT as well, even if the source isn't disclosed, because they are BeefCore and BigReactors clones, this mostly applies to the 1.12.2 and lower versions). Repacked deps aren't really a problem, because those aren't my code, so, its up to them what they want to be licensed under, not me.

MIT was chosen because its a license that I do overall agree with, both in what it allows, and what it requires, and it is one that E.B used with the original BR so it makes it simple with the requirements of the new stuff. For now, it will be staying as MIT, but I will be leaving this issue open while I decide how to proceeded from here. Choosing a license is hard, and id rather pick a license that is too loose than one that is too tight.

**Comment by RogueLogix** [comment]
Decision has been made, will be moving to the LGPL v2.1. I have gotten Beef's permission to sub-license the sections that are his code. While its not exactly what i would want in a license, it hits the major points, and will require whoever comes after me to keep the mod open source, which is most of what i want that MIT doesn't already do.
