### ISSUE TITLE
Redstone Port control rods set on pulse

### ISSUE THREAD

**Issue by Topey2X** [RogueLogix/BiggerSeries#33]
Was going to put this in comments of another issue but I think it’s seperate. 
I’ve been fiddling around with the set on pulse for the redstone ports and it seems to only add the value of what I set every time I press the button. 
E.g. set to 25%, first press sets to 25%, second to 50%, third to 75%. 
Expected result: set to 25%, first and every subsequent press sets to 25%. 

If it helps, I checked the code and it looks like this adding is intended functionality when ‘activeMode’ is 0, which it defaults to. My desired functionality is when ‘activeMode’ is 2, but it never gets changed?

**Comment by RogueLogix** [comment]
Issue seems to be in the gui half of it, the tile appears to be working fine, gizmo, this is your issue

**Comment by gizmocodes** [comment]
Yep, and you're exactly right. Arguably, mode 2 should be the default, but the root problem is I was an idiot and forgot to actually add the "Change Mode" button to the GUI, so it's forever stuck on mode 0. I'm currently in the middle of rewriting the GUI system, which will majorly clean up the code (the redstone port was really showed off the problems with my old GUI system, this new one should majorly improve it). Should have a fix out in a bit, and be included in next update.

**Comment by gizmocodes** [comment]
Should be fixed in 4feca1683c6ccb3739c47a545f91935c676bd494 and available in the next update.

Other graphical bugs with the GUI for that block still exist (such as the GUI not showing saved values after a world reload, despite the values still being set/active), but due to the strange commit system that the redstone port uses and the old system being entirely unfit to deal with that, there's not much I can do about that until I finish the new GUI system.
