### ISSUE TITLE
Reactor doesn't create, store or send power.

### ISSUE THREAD

**Issue by FawneBartley** [RogueLogix/BiggerSeries#36]
I built a reactor in the modpack All the Mods 6 and it isnt created, storing or sending any power to the machines that are linked to it via a universal mekanism cable.

![2020-12-04_16 48 06](https://user-images.githubusercontent.com/14330070/101127002-b496d700-3650-11eb-91ce-3687163dda8d.png)
![2020-12-04_16 48 24](https://user-images.githubusercontent.com/14330070/101127006-b6609a80-3650-11eb-8aac-d0699352fe82.png)

Please advise if you require any further details (the pack is 1.16.4 btw)

**Comment by nanonestor** [comment]
Does it not form a multiblock structure?  Do you have a coolant port anywhere (which turns it into a steam generator instead of a power generator) ?  Joining their discord is a better way to go than continuing this issue thread.

**Comment by gizmocodes** [comment]
It's building correctly, but I can see to the right of the terminal that there's a coolant port. While it's not clear in the current version, (my rewrite of the GUIs will hopefully fix that), having a coolant port will make the reactor generate steam from water and fuel, rather than RF. Remove the blue coolant port to the right of the reactor, and it should start generating RF. Hopefully that helps? (If so, please close the issue.)

**Comment by gizmocodes** [comment]
Closing due to no response, so I'm assuming the coolant port was the problem. If this issue wasn't solved, please feel free to reopen it or ask us in our Discord!
